version: 1
services:
  - type: static
    name: unique-interiors-solutions
    env: static
    buildCommand: npm install && npm run build
    publish: ./dist
    routes:
      - src: /(.*)
        dest: /index.html